name: Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Tidy
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: go.mod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📌 Auto-fix go.sum discrepancies"
